run: compile
        java MyWebPage
compile:
        javac MapADT.java
        javac HashTableMap.java
        javac USElectionData.java
        javac ElectionBackEnd.java
	javac TestApplication.java
        javac MyWebpage.java
test: compile
        java TestApplication
clean:
        $(RM) HashTableMap.class
        $(RM) USElectionData.class
        $(RM) ElectionBackEnd.class
        $(RM) TestApplication.class
        $(RM) MyWebpage.class
        $(RM) MapADT.class
